[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["parse-multipart-data"]

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[dev]
  command       = "vite"
  port          = 5173
  targetPort    = 8888
  functionsPort = 9999
  publish       = "dist"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
