[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  # Ensure Node 18 runtime
  node_bundler = "esbuild"
  external_node_modules = ["@google-cloud/vision", "parse-multipart-data"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[dev]
  command = "vite"
  port = 5173
  targetPort = 8888
  functionsPort = 9999
  publish = "dist"
