[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  # Use esbuild for smaller/faster function bundles
  node_bundler = "esbuild"
  # Keep these dependencies external so Netlify installs them
  external_node_modules = ["parse-multipart-data", "stripe"]

# Single Page App: send all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Optional) CORS for functions if you ever call them cross-origin
#[[headers]]
#  for = "/.netlify/functions/*"
#  [headers.values]
#    Access-Control-Allow-Origin = "*"
