[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Single Page App: send all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Optional) CORS for functions if you ever call them cross-origin
#[[headers]]
#  for = "/.netlify/functions/*"
#  [headers.values]
#    Access-Control-Allow-Origin = "*"
